#!/bin/bash
RUN_SA="501256442143-compute@developer.gserviceaccount.com"

for SECRET in DATABASE_URL DATABASE_URL_POOLED GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET BETTER_AUTH_SECRET GOOGLE_CLOUD_PROJECT GCS_BUCKET_NAME POSTMARK_SERVER_API_TOKEN POSTMARK_INBOUND_WEBHOOK_USER POSTMARK_INBOUND_WEBHOOK_PASS BOLDSIGN_API_KEY BOLDSIGN_WEBHOOK_SECRET GEMINI_API_KEY MAIL_DOMAIN; do
  echo "→ $SECRET"
  gcloud secrets add-iam-policy-binding $SECRET \
    --member="serviceAccount:$RUN_SA" \
    --role="roles/secretmanager.secretAccessor"
done
